cis/urls.py
from django.urls import path
from . import views

app_name = 'cis'

urlpatterns = [
    path('cis/<status>/', views.CIListView.as_view(), name='ci_list'),
    path('ci/create/', views.CICreateView.as_view(), name='ci_create'),
    path('ci/upload/', views.ci_upload, name='ci_upload'),
    path('ci/<int:pk>', views.CIDetailView.as_view(), name='ci_detail'),
    path('ci/pack/send/', views.send_ci_pack, name='ci_pack_send'),
    path('places/', views.manage_client_places, name='manage_client_places'),
    path('place/create/', views.PlaceCreateView.as_view(), name='place_create'),
    path('place/<int:pk>', views.PlaceUpdateView.as_view(), name='place_update'),
    path('manufacturer/<int:pk>', views.ManufacturerDetailView.as_view(), name='manufacturer_detail'),
    path('appliances/', views.ApplianceListView.as_view(), name='appliance_list'),
    path('appliance/create/', views.ApplianceCreateView.as_view(), name='appliance_create'),
    path('appliance/<int:pk>', views.ApplianceUpdateView.as_view(), name='appliance_update'),
]

internalize/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

from cis.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', homepage, name='homepage'),
    path('cis/', include('cis.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

cis/models.py
from typing import Tuple, NewType

from django.contrib import admin
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone
from fernet_fields import EncryptedCharField

from accounts.models import User


CIId = NewType('CIId', int)


class Company(models.Model):
    """Model representing an abstract Company.

    Base for Client, ISP and Manufacturer
    """

    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        abstract = True
        ordering = ['name']


class Client(Company):
    """Model representing a Client company"""

    search_fields = ('name',)

    def get_absolute_url(self):
        return reverse('cis:client_detail', args=(self.id,))

    def __str__(self):
        return self.name


class Place(models.Model):
    """Model representing a location of a Client"""

    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.client} | {self.name}"

    def get_absolute_url(self):
        return reverse('cis:place_update', args=(self.pk,))

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['client', 'name'],
                name='unique_client_place_name'
            )
        ]


class ISP(Company):
    """Model representing a Internet Service Provider company"""


class Manufacturer(Company):
    """Model representing a Manufacturer of a Configuration Item"""


class Circuit(models.Model):
    """Model representing a Circuit of a ISP installed in a Place"""

    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    isp = models.ForeignKey(ISP, on_delete=models.CASCADE)
    identifier = models.CharField(max_length=50)
    bandwidth = models.CharField(max_length=10)
    type = models.CharField(max_length=50)
    description = models.CharField(max_length=255, help_text="")

    def __str__(self):
        return f"{self.isp.name} | {self.identifier} | {self.bandwidth}"


class Contract(models.Model):
    """Model representing a Contract applied to a CI"""

    name = models.CharField(max_length=100, unique=True)
    begin = models.DateField()
    end = models.DateField()
    description = models.TextField()

    def __str__(self):
        return self.name


class ApplianceManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().select_related('manufacturer')


class Appliance(models.Model):
    """Model representing a physical or virtual Appliance that compounds a Configuration Item"""

    # modify the initial queryset to join the Manufacturer
    objects = ApplianceManager()

    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    serial_number = models.CharField(max_length=255, unique=True)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.SET_NULL, null=True)
    model = models.CharField(max_length=100)
    virtual = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.manufacturer} | {self.model} | {self.serial_number}"

    def get_absolute_url(self):
        return reverse('cis:appliance_update', args=(self.pk,))

    class Meta:
        ordering = ['serial_number']


class Credential(models.Model):
    """Model representing access credentials of a Configuration Item"""

    credential_id = models.AutoField(primary_key=True)
    username = EncryptedCharField(max_length=50)
    password = EncryptedCharField(max_length=50)
    enable_password = EncryptedCharField(max_length=50)
    instructions = EncryptedCharField(max_length=255, blank=True, null=True)


class CIPack(models.Model):
    """
    Model representing a pack of CIs.

    It is used to send CIs to production.
    """

    responsible = models.ForeignKey('accounts.User', on_delete=models.SET_NULL, null=True)
    sent_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    approved_by = models.ForeignKey(
        'accounts.User',
        on_delete=models.SET_NULL,
        null=True,
        related_name='cipacks_approved',
        limit_choices_to={'is_superuser': True}
    )

    @property
    @admin.display(description='Approved (%)')
    def percentage_of_cis_approved(self) -> int:
        num_cis_approved = self.ci_set.filter(status=2).count()
        if not num_cis_approved:
            return 0
        return round((num_cis_approved / len(self)) * 100)

    def send_to_production(self, ci_pks: Tuple[CIId, ...]):
        cis = CI.objects.filter(pk__in=ci_pks)
        self.ci_set.set(cis)
        self.ci_set.update(status=1)

    def approve_all_cis(self):
        self.ci_set.update(status=2)

    def __len__(self):
        return self.ci_set.count()

    def __str__(self):
        local_date = timezone.localtime(self.sent_at)
        return f"{self.responsible} {local_date.strftime('%Y-%m-%d %H:%M:%S')}"


class CI(Credential):
    """
    Model representing a Configuration Item.

    It is composed of a Setup and a Credential.
    https://docs.djangoproject.com/en/stable/topics/db/models/#multiple-inheritance
    """

    IMPACT_OPTIONS = (
        (0, 'low'),
        (1, 'medium'),
        (2, 'high'),
    )
    STATUS_OPTIONS = (
        (0, 'created'),
        (1, 'sent'),
        (2, 'approved'),
    )
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    appliances = models.ManyToManyField(Appliance)
    hostname = models.CharField(max_length=50)
    ip = models.GenericIPAddressField()
    description = models.CharField(max_length=255)
    deployed = models.BooleanField(default=False)
    business_impact = models.PositiveSmallIntegerField(
        choices=IMPACT_OPTIONS,
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(2)],
    )
    contract = models.ForeignKey(Contract, on_delete=models.SET_NULL, null=True)
    status = models.PositiveSmallIntegerField(
        choices=STATUS_OPTIONS,
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(2)],
    )
    pack = models.ForeignKey(CIPack, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.place} | {self.hostname} | {self.ip}"

    def get_absolute_url(self):
        return reverse('cis:ci_detail', args=(self.pk,))

    class Meta:
        ordering = ['hostname']
        constraints = [
            models.UniqueConstraint(
                fields=['client', 'hostname', 'ip', 'description'],
                name='unique_client_hostname_ip_description'
            )
        ]

cis/forms.py
from django import forms

from .models import CI, Place, Appliance


class UploadCIsForm(forms.Form):
    file = forms.FileField()


class CIForm(forms.ModelForm):
    appliances = forms.ModelMultipleChoiceField(queryset=None)
    place = forms.ModelChoiceField(queryset=None)

    def __init__(self, *args, **kwargs):
        self.client = kwargs.pop('client')
        super().__init__(*args, **kwargs)
        self.fields['appliances'] = forms.ModelMultipleChoiceField(
            queryset=Appliance.objects.filter(client=self.client)
        )
        self.fields['place'] = forms.ModelChoiceField(
            queryset=Place.objects.filter(client=self.client)
        )

    class Meta:
        model = CI
        exclude = ('client', 'status', 'pack')


class ApplianceForm(forms.ModelForm):
    class Meta:
        model = Appliance
        exclude = ('client',)


class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = ('client',)

cis/views.py
from django.db import DatabaseError
from django.shortcuts import render, redirect
from django.utils.translation import ngettext
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404
from django.forms import inlineformset_factory
from django.core.exceptions import PermissionDenied

from .models import CI, Client, Place, Manufacturer, Appliance, CIPack
from .forms import UploadCIsForm, CIForm, ApplianceForm, PlaceForm
from .loader import CILoader
from .mixins import UserApprovedMixin, AddClientMixin


def homepage(request):
    user = request.user
    if not user.is_anonymous and not user.is_approved:
        messages.warning(request, 'Your account needs to be approved. '
                                  'Please contact you Account Manager.')
    return render(request, 'homepage.html')


class PlaceCreateView(UserApprovedMixin, SuccessMessageMixin, AddClientMixin, CreateView):
    model = Place
    fields = ('name', 'description')
    success_message = "The place %(name)s was created successfully."


class PlaceUpdateView(UserApprovedMixin, SuccessMessageMixin, UpdateView):
    model = Place
    fields = ('name', 'description')
    success_message = "The place %(name)s was updated successfully."

    def get_queryset(self):
        qs = Place.objects.select_related('client')
        if not self.request.user.is_superuser:
            qs.filter(client=self.request.user.client)
        return qs


@login_required
def manage_client_places(request):
    if not request.user.is_approved: raise PermissionDenied()

    client = request.user.client
    select_client_form = None
    if request.user.is_superuser:
        select_client_form = PlaceForm()

    if request.method == 'GET':
        if request.user.is_superuser:
            if (client_id_selected := request.GET.get('client')):
                # At this point, a client was selected by a superuser
                select_client_form = PlaceForm(request.GET)
                client = Client.objects.get(pk=client_id_selected)

    PlaceInlineFormSet = inlineformset_factory(
        Client, Place, fields=('name', 'description'), extra=0)
    formset = PlaceInlineFormSet(instance=client)

    if request.method == 'POST':
        formset = PlaceInlineFormSet(request.POST, instance=client)
        if formset.is_valid():
            formset.save()
            messages.success(request, "The places were updated successfully.")
            return redirect('cis:manage_client_places')

    return render(request, 'cis/manage_client_places.html', {
        'formset': formset,
        'select_client_form': select_client_form,
        'client': client,
    })


class CICreateView(UserApprovedMixin, SuccessMessageMixin, AddClientMixin, CreateView):
    model = CI
    form_class = CIForm
    success_message = "The CI was created successfully."

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # only places of the user.client will be shown in the form
        kwargs.update({'client': self.request.user.client })
        return kwargs


class CIListView(UserApprovedMixin, ListView):
    model = CI
    paginate_by = 10

    def get_queryset(self):
        qs = CI.objects.filter(
            status=self.kwargs['status'],
            place__client=self.request.user.client
        )
        if self.request.user.is_superuser:
            qs = CI.objects.filter(status=self.kwargs['status'])

        return qs


class CIDetailView(UserApprovedMixin, DetailView):
    model = CI
    queryset = CI.objects.select_related('place', 'contract')

    def get_object(self, **kwargs):
        object = super().get_object(**kwargs)
        if not self.request.user.is_superuser:
            if object.place.client != self.request.user.client:
                # user authenticated but unauthorized
                raise Http404
        # user authenticated and authorized
        return object


class ManufacturerDetailView(UserApprovedMixin, DetailView):
    model = Manufacturer

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        qs = Appliance.objects.filter(
            manufacturer=context['manufacturer'],
            client=self.request.user.client,
        )
        if self.request.user.is_superuser:
            qs = Appliance.objects.filter(manufacturer=context['manufacturer'])
        context['num_appliances'] = qs.count()

        return context


class ApplianceListView(UserApprovedMixin, ListView):
    model = Appliance
    paginate_by = 10

    def get_queryset(self):
        qs = Appliance.objects.filter(client=self.request.user.client)
        if self.request.user.is_superuser:
            qs = super().get_queryset()
        return qs


class ApplianceCreateView(UserApprovedMixin, SuccessMessageMixin, AddClientMixin, CreateView):
    model = Appliance
    form_class = ApplianceForm
    success_message = "The appliance %(serial_number)s was created successfully."


class ApplianceUpdateView(UserApprovedMixin, SuccessMessageMixin, UpdateView):
    model = Appliance
    form_class = ApplianceForm
    success_message = "The appliance was updated successfully."

    def get_queryset(self):
        qs = Appliance.objects.select_related('client', 'manufacturer')
        if not self.request.user.is_superuser:
            qs.filter(client=self.request.user.client)
        return qs

@login_required
def ci_upload(request):
    if not request.user.is_approved: raise PermissionDenied()

    result = None
    form = UploadCIsForm()

    if request.method == 'POST':
        form = UploadCIsForm(request.POST, request.FILES)
        if form.is_valid():
            client = request.user.client
            result = CILoader(request.FILES['file'], client).save()

    return render(request, 'cis/ci_upload.html', {
        'form': form,
        'result': result
    })


@login_required
def send_ci_pack(request):
    if not request.user.is_approved: raise PermissionDenied()

    if request.method == 'POST':
        try:
            pack = CIPack.objects.create(responsible=request.user)
            ci_pks = request.POST.getlist('cis_selected')
            if ci_pks:
                pack.send_to_production(ci_pks)
                messages.success(request, ngettext(
                    'The selected CI was sent to production successfully.',
                    'The selected CIs were sent to production successfully.',
                    len(ci_pks)
                ))
            else:
                messages.error(request, 'Please select at least one item to be sent to production.')
        except DatabaseError:
            raise DatabaseError('There was an error during the sending of the CIs to production.')

    return redirect('cis:ci_list', status=0)

cis/templates/cis/_pagination.html
<div class="col-md-auto">
    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
</div>
<div class="col-md-auto">
    <div class="btn-toolbar float-right" role="toolbar" aria-label="Toolbar with button groups">
      <div class="btn-group mr-2" role="group" aria-label="First group">
        {% if page_obj.has_previous %}
            <a href="?page=1" type="button" class="btn btn-secondary" title="First">
                <i class="bi bi-caret-left-fill"></i>
            </a>
            <a href="?page={{ page_obj.previous_page_number }}" type="button" class="btn btn-secondary" title="Previous">
                <i class="bi bi-caret-left"></i>
            </a>
        {% endif %}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" type="button" class="btn btn-secondary" title="Next">
                <i class="bi bi-caret-right"></i>
            </a>
            <a href="?page={{ page_obj.paginator.num_pages }}" type="button" class="btn btn-secondary" title="Last">
                <i class="bi bi-caret-right-fill"></i>
            </a>
        {% endif %}
      </div>
    </div>
</div>

cis/templates/cis/appliance_form.html
{% extends "base_generic.html" %}

{% load crispy_forms_tags %}

{% block title %}Appliance{% endblock %}

{% block content %}

<div class="row justify-content-md-center mt-4">
  <div class="col-md-4">
    <h1 class="h5">Appliance</h1>
  </div>
</div>

<form method="post">
  {% csrf_token %}
  <div class="row justify-content-md-center mt-4">
    <div class="col-md-4">
      {{ form|crispy }}
      <input class="btn btn-primary float-right" type="submit" value="Save">
    </div>
  </div>
</form>

{% endblock %}

cis/templates/cis/appliance_list.html
{% extends "base_generic.html" %}

{% block title %}Appliances{% endblock %}

{% block content %}
<div class="row justify-content-md-center mt-4">
    <div class="col-md-12">
        <h1 class="h5">Appliances</h1>
    </div>
</div>


{% if appliance_list %}
    <div class="row justify-content-md-center mt-4">
        <div class="col-md-12">
            <table class="table table-bordered table-hover" id="dataTable">
                <thead>
                <tr>
                    {% if user.is_superuser %}
                        <th>Client</th>
                    {% endif %}
                    <th>Serial Number</th>
                    <th>Manufacturer</th>
                    <th>Model</th>
                    <th>Virtual</th>
                </tr>
                </thead>
                <tbody>
                {% for appliance in appliance_list %}
                    <tr>
                        {% if user.is_superuser %}
                            <td>{{ appliance.client.name }}</td>
                        {% endif %}
                        <td><a href="{{ appliance.get_absolute_url }}">{{ appliance.serial_number }}</a></td>
                        <td>{{ appliance.manufacturer }}</td>
                        <td>{{ appliance.model }}</td>
                        <td>{{ appliance.virtual }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row justify-content-md-end align-items-md-center">
        {% include 'cis/_pagination.html' %}
    </div>
{% else %}
    <p class="lead">No appliance was found.</p>
{% endif %}

{% endblock %}

cis/templates/cis/ci_detail.html
{% extends "base_generic.html" %}

{% block title %}{{ ci.hostname }}{% endblock %}

{% block content %}
<h1 class="h5 my-4">{{ ci }}</h1>

<div class="row">
    <div class="col-md-6">
        <h2 class="h5 my-4">Appliances</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Serial Number</th>
                    <th>Manufacturer</th>
                    <th>Model</th>
                    <th>Virtual</th>
                </tr>
            </thead>
            <tbody>
            {% for appliance in ci.appliances.all %}
                <tr>
                    <td>{{ appliance.serial_number }}</td>
                    <td>
                        <a href="{% url 'cis:manufacturer_detail' appliance.manufacturer.id %}">
                            {{ appliance.manufacturer }}
                        </a>
                    </td>
                    <td>{{ appliance.model }}</td>
                    <td>{{ appliance.virtual }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <h2 class="h5 my-4">Setup</h2>
        <table class="table">
            <tr>
                <th>Hostname</th>
                <td id="hostname">{{ ci.hostname }}</td>
            </tr>
            <tr>
                <th>IP</th>
                <td>{{ ci.ip }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ ci.description }}</td>
            </tr>
            <tr>
                <th>Deployed</th>
                <td>{{ ci.status }}</td>
            </tr>
            <tr>
                <th>Business Impact</th>
                <td>{{ ci.business_impact }}</td>
            </tr>
        </table>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <h2 class="h5 my-4">Contract</h2>
        <table class="table">
            <tr>
                <th>Name</th>
                <td>{{ ci.contract.name }}</td>
            </tr>
            <tr>
                <th>Begin</th>
                <td>{{ ci.contract.begin }}</td>
            </tr>
            <tr>
                <th>End</th>
                <td>{{ ci.contract.end }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ ci.contract.description }}</td>
            </tr>
        </table>
    </div>
    <div class="col-md-6">
        <h2 class="h5 my-4">Credentials</h2>
        <table class="table">
            <tr>
                <th>Username</th>
                <td>{{ ci.username }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ ci.password }}</td>
            </tr>
            <tr>
                <th>Enable Password</th>
                <td>{{ ci.enable_password }}</td>
            </tr>
            <tr>
                <th>Instructions</th>
                <td>{{ ci.instructions }}</td>
            </tr>
        </table>
    </div>
</div>
{% endblock %}

cis/templates/cis/ci_form.html
{% extends "base_generic.html" %}

{% load crispy_forms_tags %}

{% block title %}CI{% endblock %}

{% block content %}

<div class="row justify-content-md-center mt-4">
    <div class="col-md-6">
      <h1 class="h5">Configuration Item</h1>
    </div>
</div>

<form method="post">
  {% csrf_token %}
  {{ form.non_field_errors }}
  <div class="row justify-content-md-center mt-4">
    <div class="col-md-3">
      {{ form.hostname|as_crispy_field }}
      {{ form.ip|as_crispy_field }}
      {{ form.description|as_crispy_field }}
      {{ form.deployed|as_crispy_field }}
    </div>
    <div class="col-md-3">
      {{ form.place|as_crispy_field }}
      {{ form.contract|as_crispy_field }}
      {{ form.business_impact|as_crispy_field }}
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-md-6">
      {{ form.appliances|as_crispy_field }}
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-md-2">
      {{ form.username|as_crispy_field }}
    </div>
    <div class="col-md-2">
      {{ form.password|as_crispy_field }}
    </div>
    <div class="col-md-2">
      {{ form.enable_password|as_crispy_field }}
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-md-6">
      {{ form.instructions|as_crispy_field }}
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-md-6">
      <input class="btn btn-primary float-right" type="submit" value="Save">
    </div>
  </div>

</form>

{% endblock %}

cis/templates/cis/ci_list.html
{% extends "base_generic.html" %}

{% block title %}Configuration Items{% endblock %}

{% block content %}

<div class="row justify-content-md-center mt-4">
    <div class="col-md-12">
        <h1 class="h5">Configuration Items {{ ci_list.0.get_status_display|lower|capfirst }}</h1>
    </div>
</div>

{% if ci_list %}
    <form action="{% url 'cis:ci_pack_send' %}" method="post">
    {% csrf_token %}

    <div class="row justify-content-md-center mt-4">
        <div class="col-md-12">
            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    {# If CIs status == 0 (created), show checkbox column #}
                    {% if '0' in request.path_info %}
                        <th><input id="js-toggler" type="checkbox" title="Deselect all" checked></th>
                    {% endif %}
                    {% if user.is_superuser %}
                        <th>Client</th>
                    {% endif %}
                    <th>Hostname</th>
                    <th>IP</th>
                    <th>Description</th>
                    <th>Status</th>
                    <th>Appliances</th>
                </tr>
                </thead>
                <tbody>
                {% for ci in ci_list %}
                    <tr>
                        {% if '0' in request.path_info %}
                            <td><input class="js-items" type="checkbox" name="cis_selected" value="{{ ci.pk }}" checked></td>
                        {% endif %}
                        {% if user.is_superuser %}
                            <td>{{ ci.client.name }}</td>
                        {% endif %}
                        <td><a href="{% url 'cis:ci_detail' ci.pk %}">{{ ci.hostname }}</a></td>
                        <td>{{ ci.ip }}</td>
                        <td>{{ ci.description }}</td>
                        <td>{{ ci.get_status_display }}</td>
                        <td>
                            <ul class="list-unstyled">
                            {% for appliance in ci.appliances.all %}
                                <li>{{ appliance.serial_number }} {{ appliance.manufacturer }} {{ appliance.model }}</li>
                            {% endfor %}
                            </ul>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row justify-content-md-end align-items-md-center">
        {% if '0' in request.path_info %}
            <div class="col-md-auto float-left">
                <input class="btn btn-outline-primary" type="submit" value="Send selected items to production">
            </div>
        {% endif %}
        {% include 'cis/_pagination.html' %}
    </div>

    </form>
{% else %}
    <p class="lead">No configuration item was found.</p>
{% endif %}
{% endblock content %}

cis/templates/cis/ci_upload.html
{% extends "base_generic.html" %}

{% load crispy_forms_tags %}

{% block title %}Upload{% endblock %}

{% block content %}
    <div class="row justify-content-md-center mt-4">
        <div class="col-md-4">
            <h1 class="h5">Upload</h1>
        </div>
    </div>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row justify-content-md-center mt-4">
            <div class="col-md-4">
                {{ form|crispy }}
                <input class="btn btn-primary float-right" type="submit" value="Upload">
            </div>
        </div>
    </form>

    {% if result %}
        <div class="row">
            <div class="col-md-6">
                <h2 class="h5 my-4">Summary</h2>

                <table class="table">
                    <tr>
                        <th>Number of CIs inserted</th>
                        <td>{{ result.cis|length }}</td>
                    </tr>
                    {% if result.errors %}
                        <tr>
                            <th>Number of errors</th>
                            <td class="text-danger">{{ result.errors|length }}</td>
                        </tr>
                    {% endif %}
                </table>
            </div>
        </div>

        {% if result.errors %}
        <h2 class="h5 my-4">Errors Details</h2>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Error</th>
                    <th>Row</th>
                </tr>
            </thead>
            <tbody>
                {% for error in result.errors %}
                    <tr>
                        <td>{{ error.exc }}</td>
                        <td>{{ error.row }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    {% endif %}
{% endblock %}

cis/templates/cis/manage_client_places.html
{% extends "base_generic.html" %}
{% load crispy_forms_filters %}

{% load crispy_forms_tags %}

{% block title %}{{ client }}{% endblock %}

{% block content %}

<div class="row justify-content-md-center mt-4">
    <div class="col-md-4">
      <h1 class="h5">All Places</h1>
    </div>
</div>

{% if select_client_form %}
    <div class="row justify-content-md-center mt-4">
        <div class="col-md-4">
            <form method="get">
                {{ select_client_form|crispy }}
                <input type="submit" value="Ok">
            </form>
        </div>
    </div>
{% endif %}

<form method="post" class="mb-5">
    {% csrf_token %}
    <div class="row justify-content-md-center mt-4">
        <div class="col-md-4">
            {% if formset|length > 0 %}
                {{ formset|crispy }}
                <input class="btn btn-primary float-right" type="submit" value="Save">
            {% else %}
                <p class="lead">No place was found.</p>
            {% endif %}
        </div>
    </div>
</form>

{% endblock %}

cis/templates/cis/manage_client_sites.html
{% extends "base_generic.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ client }}{% endblock %}

{% block content %}

<div class="row justify-content-md-center mt-4">
    <div class="col-md-4">
      <h1 class="h5">All Sites</h1>
    </div>
</div>

<form method="post" class="mb-5">
    {% csrf_token %}
    <div class="row justify-content-md-center mt-4">
        <div class="col-md-4">
            {% if formset|length > 0 %}
                {{ formset|crispy }}
                <input class="btn btn-primary float-right" type="submit" value="Save">
            {% else %}
                <p class="lead">No site was found.</p>
            {% endif %}
        </div>

    </div>
</form>

{% endblock %}

cis/templates/cis/manufacturer_detail.html
{% extends "base_generic.html" %}

{% block title %}{{ manufacturer }}{% endblock %}

{% block content %}
<h1 class="h5 my-4">{{ manufacturer }}</h1>

<p>Number of CIs: {{ num_appliances }}</p>

{% endblock %}

cis/templates/cis/place_form.html
{% extends "base_generic.html" %}

{% load crispy_forms_tags %}

{% block title %}Place{% endblock %}

{% block content %}

<div class="row justify-content-md-center mt-4">
  <div class="col-md-4">
    <h1 class="h5">Place</h1>
  </div>
</div>

<form method="post">
  {% csrf_token %}
  <div class="row justify-content-md-center mt-4">
    <div class="col-md-4">
      {{ form|crispy }}
      <input class="btn btn-primary float-right" type="submit" value="Save">
    </div>
  </div>
</form>

{% endblock %}