cis/urls.py
from django.urls import path
from . import views

app_name = 'cis'

urlpatterns = [
    path('cis/<status>/', views.CIListView.as_view(), name='ci_list'),
    path('ci/create/', views.CICreateView.as_view(), name='ci_create'),
    path('ci/upload/', views.ci_upload, name='ci_upload'),
    path('ci/<int:pk>', views.CIDetailView.as_view(), name='ci_detail'),
    path('ci/pack/send/', views.send_ci_pack, name='ci_pack_send'),
    path('places/', views.manage_client_places, name='manage_client_places'),
    path('place/create/', views.PlaceCreateView.as_view(), name='place_create'),
    path('place/<int:pk>', views.PlaceUpdateView.as_view(), name='place_update'),
    path('manufacturer/<int:pk>', views.ManufacturerDetailView.as_view(), name='manufacturer_detail'),
    path('appliances/', views.ApplianceListView.as_view(), name='appliance_list'),
    path('appliance/create/', views.ApplianceCreateView.as_view(), name='appliance_create'),
    path('appliance/<int:pk>', views.ApplianceUpdateView.as_view(), name='appliance_update'),
]

internalize/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

from cis.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', homepage, name='homepage'),
    path('cis/', include('cis.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

templates/_messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'homepage' %}" style="font-family: 'Dancing Script', cursive;">Internalize</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% if user.is_approved %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="cisDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          CIs
        </a>
        <div class="dropdown-menu" aria-labelledby="cisDropdown">
          <a class="dropdown-item" href="{% url 'cis:ci_create' %}">Add</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'cis:ci_list' 0 %}">Created</a>
          <a class="dropdown-item" href="{% url 'cis:ci_list' 1 %}">Sent</a>
          <a class="dropdown-item" href="{% url 'cis:ci_list' 2 %}">Approved</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="appliancesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Appliances
        </a>
        <div class="dropdown-menu" aria-labelledby="appliancesDropdown">
          <a class="dropdown-item" href="{% url 'cis:appliance_create' %}">Add</a>
          <a class="dropdown-item" href="{% url 'cis:appliance_list' %}">All</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="placesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Places
        </a>
        <div class="dropdown-menu" aria-labelledby="placesDropdown">
          <a class="dropdown-item" href="{% url 'cis:place_create' %}">Add</a>
          <a class="dropdown-item" href="{% url 'cis:manage_client_places' %}">All</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cis:ci_upload' %}">Upload</a>
      </li>
    </ul>
    {% endif %}

    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="nav-link">{{ user }}</span>
        </li>
        {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin Area</a>
          </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
        </li>
      {% else %}
      <!--
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
      </li>
      -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/base_generic.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!-- Logo -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">

    <!-- Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">

    <title>{% block title %}CIs{% endblock %}</title>
  </head>
  <body>
    <div class="container-fluid">
      {% include '_navbar.html' %}
      {% include '_messages.html' %}
      {% block content %}{% endblock %}
    </div>

    <!-- jQuery first, then a Bootstrap JavaScript bundle -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <script>
        const toggler = document.getElementById('js-toggler');
        toggler.addEventListener('click', toggleAllItems);

        const cis = document.getElementsByClassName('js-items');
        for (let ci of cis) {
            ci.addEventListener('click', adjustTogglerAccordingToItems);
        }

        function toggleAllItems() {
            for (let ci of cis) {
                ci.checked = toggler.checked;
            }
            changeTogglerTitle();
        }

        function adjustTogglerAccordingToItems() {
            if (allItemsChecked()) {
                toggler.checked = true;
                changeTogglerTitle();
            }
            if (this.checked !== toggler.checked) {
                toggler.checked = false;
                changeTogglerTitle();
            }
        }

        function changeTogglerTitle() {
            toggler.title = 'Select all';
            if (toggler.checked) {
                toggler.title = 'Deselect all';
            }
        }

        function allItemsChecked() {
            for (let ci of cis) {
                if (!ci.checked) {
                    return false;
                }
            }
            return true;
        }
    </script>
  </body>
</html>

templates/homepage.html
{% extends "base_generic.html" %}

{% block title %}Homepage{% endblock %}

{% block content %}
<h1 class="h5 my-4">Homepage</h1>

{% endblock %}